name: belajar_ceria
description: A simple educational quiz game for elementary students.
publish_to: 'none'
version: 0.0.1
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.9.0
  shared_preferences: ^2.5.3
  audioplayers: ^6.5.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/BENAR.mp3
    - assets/wrong.wav
    - assets/anak sd angkat tangan.jpeg
    - assets/anak sd tolong menolong.jpg
    - assets/Gambar anak anak sd.jpeg
    - assets/Gambar anak sd lagi.png
    - assets/Gambar guru l.jpeg
    - assets/Gambar guru p.jpeg
    - assets/Gambar pohon 1.jpeg
    - assets/Gambar pohon 2.jpeg
    - assets/Gambar pohon 3.jpeg
    - assets/Naik bus.jpeg
